version: "2"

services:
  gpsd:
    image: bradsjm/rpi-gpsd 
    command: /dev/ttyAMA0
    ports:
      - 2947:2947
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"

  redis:
    image: arm32v7/redis

  commander:
    image: gone/rpi-docker-redis-commander
    command: --redis-host redis
    ports:
      - "8080:8081"
    links:
      - redis
  
  logger:
    build: ./logger
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - GPSD_HOST=gpsd
     - GPSD_PORT=2947
    links:
     - redis
     - gpsd
    volumes:
     - "./logger:/app"
