version: "2"

services:
  gpsd:
    image: bradsjm/rpi-gpsd 
    command: /dev/ttyAMA0
    ports:
      - 2947:2947
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"

  redis:
    image: arm32v7/redis

  commander:
    image: gone/rpi-docker-redis-commander
    command: --redis-host redis
    ports:
      - "8080:8081"
    links:
      - redis
  
  logger:
    image: matthewbaggett/rpi-gps-logger
    build: ./logger
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - GPSD_HOST=gpsd
     - GPSD_PORT=2947
    links:
     - redis
     - gpsd
    volumes:
     - "./logger:/app"

  syncer:
    image: matthewbaggett/rpi-redis-syncer
    build: ./sync
    environment:
     - LOCAL_REDIS_PROTOCOL=tcp
     - LOCAL_REDIS_HOST=redis
     - LOCAL_REDIS_PORT=6379
     - REMOTE_REDIS_PROTOCOL=http
     - REMOTE_REDIS_HOST=webdis.controlpanel.home.gone.io
     - REMOTE_REDIS_PORT=80
     - REMOTE_REDIS_USER=RemoteAccess
     - REMOTE_REDIS_PASS=6iz7ulwS683N38C
     - "REMOTE_ADDED_PREFIX=car:greenbox:"
     - DELETE_ON_COPY=true
    links:
     - redis
    volumes:
     - "./sync:/app"
